---
language: node_js
node_js:
- '0.10'
jdk:
- oraclejdk7
before_script:
- npm install -g grunt-cli
before_install:
- wget dist.neo4j.org/neo4j-community-2.1.7-unix.tar.gz
- tar -xzf neo4j-community-2.1.7-unix.tar.gz
- neo4j-community-2.1.7/bin/neo4j start
addons:
  sauce_connect: true
before_deploy:
- neo4j-community-2.1.7/bin/neo4j stop
- rm -rf neo4j-community-2.1.7 neo4j-community-2.1.7-unix.tar.gz
deploy:
  provider: heroku
  app: agilejs-team-2
  skip_cleanup: true
  api_key:
    secure: ! 'Hcwzj8bB594hRIsgf4m/cj/R0Ab6z86c/7BKeSnOzxtWlvHLTKLMEJc2M4gp

      fe7vLcpuIos0+Bf+vIYPVLBfTC+1JGNnZgJJBJ3QbhsHZYsEm3D7YuI7ZSaf

      A7X9A9DN0tBC0CEDYua5bhSorZIYiY2H8IXB4scY3hYap4JFrlQ='
env:
  global:
  - secure: ! 'I+OXMusiJ1bxTvqYLioAZ+njnP9x8DnqDP+8AaYKDZOXfTJcuMybcBu6tJ8T

      4Ko+HfLWRXOJLvnUOUQFPxoEGy7vUVIXDCMYghS95TL2A7BLmLCIADvhKPzq

      lvbmL1sO1wRTYm6N5FauQ2o0E8BQEf73K+w6VAjakcZ6eB6EloQ='
  - secure: ! 'ULU2vRmZuivuGyjROLsQ6m2JqCbm9YRMe/8Nmen9lxzyyig5IapZQWzvnyzq

      wby+6l9aPwmRTHBDb9hinJ57OFO9ZuJN1Q7fExIvH8m4O/QqLf7M4rTGZE5r

      TdRya3Qkad+CgJAh2+C072IBwzVM7ZD/qXlJdGYfmohcVVTgEHc='
