---
language: node_js
node_js:
- '0.10'
jdk:
- oraclejdk7
before_script:
- npm install -g grunt-cli
before_install:
- wget dist.neo4j.org/neo4j-community-2.1.7-unix.tar.gz
- tar -xzf neo4j-community-2.1.7-unix.tar.gz
- neo4j-community-2.1.7/bin/neo4j start
addons:
  sauce_connect: true
before_deploy:
- neo4j-community-2.1.7/bin/neo4j stop
- rm -rf neo4j-community-2.1.7 neo4j-community-2.1.7-unix.tar.gz
deploy:
  provider: heroku
  app: agilejs-team-2
  skip_cleanup: true
  api_key:
    secure: ! 'Hcwzj8bB594hRIsgf4m/cj/R0Ab6z86c/7BKeSnOzxtWlvHLTKLMEJc2M4gp

      fe7vLcpuIos0+Bf+vIYPVLBfTC+1JGNnZgJJBJ3QbhsHZYsEm3D7YuI7ZSaf

      A7X9A9DN0tBC0CEDYua5bhSorZIYiY2H8IXB4scY3hYap4JFrlQ='
env:
  global:
  - secure: ! 'QLNtl6+Kqbe72gUdTb6pDLOMpRBYeVGRIveKCb91CA9k5dUcANDUDIyktAYH

      khKO1wQmHoIVV/y6YzdgfuczUqxnazeV9LTrofSj/fg6DgALvB/aus3Z+dMB

      Euf2mCDEy64d1ZCAarJ116/tAGpQCK2qCBg0rymFuSwKII1DXr8='
  - secure: ! 'S8ghsBDC2G/v3t5y1hGAdTZX/j7iF8bRmTw353OUXKXSiv6GsIn7Ch8UHtCy

      T1sHI5ET5sDKtPreQhcSRsBU1dEa3mc7nZvLNhqWYIew0auGQeKt9Ho8Wtx9

      BGIk6nVd2jE5RJiZMMQ/MyxEsmaEhoYvs/vv33UiF9H5VQgYQl0='
